INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES(2, 'REMEDIOS');
INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES(3, 'ARMAS');
INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES(4, 'SEILA TO SEM IDEIA');

INSERT INTO USUARIO(ID, EMAIL, NOME, SENHA) VALUES(2, 'DAVI@EMAIL', 'DAVI', 'SENHA');
